services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    env_file: .env
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
