"""empty message

Revision ID: cfef44a812c6
Revises:
Create Date: 2025-05-23 00:18:02.456810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfef44a812c6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("customer_id"),
    )
    op.create_table(
        "insurance_policies",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("policy_type", sa.String(), nullable=False),
        sa.Column("premium_amount", sa.Integer(), nullable=False),
        sa.Column("policy_start_date", sa.Date(), nullable=False),
        sa.Column("policy_end_date", sa.Date(), nullable=False),
        sa.Column(
            "policy_status",
            sa.Enum("active", "expired", "canceled", "pending", name="policystatus"),
            nullable=False,
        ),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("policy_id"),
    )
    op.drop_table("insurance_policy")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_policy",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "policy_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "premium_amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("policy_start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("policy_end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "policy_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("insurance_policy_pkey")),
    )
    op.drop_table("insurance_policies")
    op.drop_table("customers")
    # ### end Alembic commands ###
