name: CI Workflow for Backend and Frontend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies with Poetry
      run: |
        cd backend
        poetry install --no-interaction
  
    - name: Run Alembic Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      run: |
        poetry run alembic upgrade head

    - name: Start backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cd backend
        poetry run uvicorn backend.app.main:app --host 0.0.0.0 --port 8000

    - name: Test with pytest
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        poetry run pytest

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start frontend
        run: |
          cd frontend
          npm start