name: CI Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-interaction

    - name: Test with pytest
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        export PYTHONPATH=$(pwd)/backend  
        poetry run pytest